### ISSUE TITLE
Default size of images in document

### ISSUE THREAD

**Issue by pat-s** [humburg/reportmd#31]
Right all images are cropped down to 50% width with a left-margin of 25%:

```css
@media (min-width: 992px)
.col-md-offset-3 {
    margin-left: 25%;
}
@media (min-width: 992px)
.col-md-6 {
    width: 50%;
}
```

I am currently using
```css
@media (min-width: 992px) {
  .col-md-offset-3 {
      margin-left: 10%;
  }
  .col-md-6 {
      width: 80%;
  }
}
```

With this image size it makes also sense to provide an option in the header to scale figure sizes:

```yml 
output:
  reportMD::multi_document:
    toc: true
    fig_caption: true
    highlight: dracula
    depends:
      part2: vegetation-indices.Rmd
    css: R.css
    use_namespace: false
    fig.width: 7
    fig.height: 4
```

Example: [plot-speclibs.html.zip](https://github.com/humburg/reportmd/files/794287/plot-speclibs.html.zip)

What's your opinion in changing the default image size and providing options for `fig.width` and  `fig.height` in the header? Imo the current image size is too small. Even though one can get a zoom when clicking the image, it should be larger by default.
